@echo off
echo Activating virtual environment...
call ..\.venv\Scripts\activate.bat
echo Installing httpx...
python -m pip install httpx
echo Starting server...
python -m uvicorn main:app --host 0.0.0.0 --port 8005
pause

