"""
ExamGuard Pro - Transformer Training for Plagiarism Detection

This script trains the Transformer encoder for semantic text similarity,
which is used for plagiarism detection in exam answers.

Training data includes:
1. Paraphrase pairs (similar meaning, different words)
2. Non-paraphrase pairs (different meanings)
3. Synthetic exam answer variations

The model learns to encode text into embeddings where similar texts
have high cosine similarity.
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import random
import json
import os
from pathlib import Path
from datetime import datetime
from typing import List, Tuple, Optional
import math

# Add parent to path for imports
import sys
sys.path.insert(0, str(Path(__file__).parent))

from config import TransformerConfig, TinyTransformerConfig, SmallTransformerConfig
from model import Transformer
from data.tokenizer import SimpleTokenizer
from training.trainer import create_optimizer
from training.scheduler import CosineAnnealingWarmup


# =============================================================================
# SIMILARITY DATASET
# =============================================================================

class SimilarityDataset(Dataset):
    """Dataset for training text similarity/plagiarism detection."""
    
    def __init__(
        self,
        text_pairs: List[Tuple[str, str, float]],  # (text1, text2, similarity_score)
        tokenizer: SimpleTokenizer,
        max_length: int = 128
    ):
        self.pairs = text_pairs
        self.tokenizer = tokenizer
        self.max_length = max_length
    
    def __len__(self):
        return len(self.pairs)
    
    def __getitem__(self, idx):
        text1, text2, similarity = self.pairs[idx]
        
        # Tokenize
        tokens1 = self.tokenizer.encode(text1)[:self.max_length]
        tokens2 = self.tokenizer.encode(text2)[:self.max_length]
        
        # Pad
        tokens1 = tokens1 + [self.tokenizer.pad_token_id] * (self.max_length - len(tokens1))
        tokens2 = tokens2 + [self.tokenizer.pad_token_id] * (self.max_length - len(tokens2))
        
        return {
            'text1': torch.tensor(tokens1, dtype=torch.long),
            'text2': torch.tensor(tokens2, dtype=torch.long),
            'similarity': torch.tensor(similarity, dtype=torch.float)
        }


# =============================================================================
# TRAINING DATA GENERATION
# =============================================================================

def create_paraphrase_data() -> List[Tuple[str, str, float]]:
    """
    Create training data with paraphrase pairs.
    Returns list of (text1, text2, similarity_score) tuples.
    
    Similarity scores:
    - 1.0: Exact paraphrase (same meaning)
    - 0.7-0.9: High similarity (related topics)
    - 0.3-0.5: Low similarity (different topics)
    - 0.0-0.2: No similarity (unrelated)
    """
    
    pairs = []
    
    # === PARAPHRASE PAIRS (similarity ~1.0) ===
    paraphrases = [
        # Biology
        ("The mitochondria is the powerhouse of the cell.",
         "Mitochondria are responsible for producing energy in cells.", 1.0),
        ("The mitochondria produces ATP through cellular respiration.",
         "ATP is generated by mitochondria via the process of cellular respiration.", 1.0),
        ("Photosynthesis converts light energy into chemical energy.",
         "Plants convert sunlight into chemical energy through photosynthesis.", 1.0),
        ("DNA contains the genetic instructions for living organisms.",
         "The genetic blueprint of organisms is stored in DNA.", 1.0),
        ("Enzymes are proteins that catalyze biochemical reactions.",
         "Biochemical reactions are sped up by enzyme proteins.", 1.0),
        ("The cell membrane controls what enters and exits the cell.",
         "Entry and exit of substances is regulated by the cell membrane.", 1.0),
        ("Ribosomes are responsible for protein synthesis.",
         "Protein production occurs at the ribosomes.", 1.0),
        ("The nucleus contains the cell's genetic material.",
         "Genetic material of a cell is housed in the nucleus.", 1.0),
        
        # Chemistry
        ("Water is composed of hydrogen and oxygen atoms.",
         "H2O consists of hydrogen and oxygen.", 1.0),
        ("Chemical bonds form when atoms share or transfer electrons.",
         "Atoms create chemical bonds by sharing or transferring electrons.", 1.0),
        ("The periodic table organizes elements by atomic number.",
         "Elements are arranged in the periodic table based on atomic number.", 1.0),
        ("Acids have a pH less than 7.",
         "A pH below 7 indicates an acidic solution.", 1.0),
        ("Exothermic reactions release heat energy.",
         "Heat is released during exothermic reactions.", 1.0),
        
        # Physics
        ("Force equals mass times acceleration.",
         "The product of mass and acceleration gives force.", 1.0),
        ("Energy cannot be created or destroyed, only transformed.",
         "The law of conservation of energy states energy only changes form.", 1.0),
        ("Light travels at approximately 300,000 km per second.",
         "The speed of light is about 300,000 kilometers per second.", 1.0),
        ("Gravity is the force that attracts objects toward each other.",
         "Objects are pulled together by gravitational force.", 1.0),
        
        # Mathematics
        ("The derivative measures the rate of change of a function.",
         "Rate of change in a function is measured by its derivative.", 1.0),
        ("Pi is the ratio of a circle's circumference to its diameter.",
         "The circumference divided by diameter of a circle gives pi.", 1.0),
        ("Prime numbers are only divisible by 1 and themselves.",
         "A number that can only be divided by 1 and itself is prime.", 1.0),
        
        # History
        ("World War II ended in 1945.",
         "The year 1945 marked the end of World War II.", 1.0),
        ("The Renaissance was a period of cultural rebirth in Europe.",
         "European cultural revival occurred during the Renaissance period.", 1.0),
        
        # Computer Science
        ("An algorithm is a step-by-step procedure for solving a problem.",
         "A systematic procedure to solve problems is called an algorithm.", 1.0),
        ("Binary code uses only 0s and 1s to represent data.",
         "Data is represented using 0s and 1s in binary.", 1.0),
        ("Machine learning enables computers to learn from data.",
         "Computers can learn patterns from data using machine learning.", 1.0),
    ]
    
    # Add original and slightly modified versions
    for p1, p2, sim in paraphrases:
        pairs.append((p1, p2, sim))
        pairs.append((p2, p1, sim))  # Symmetric
        
        # Add slight variations (0.9 similarity)
        pairs.append((p1, p1.lower(), 0.95))
        pairs.append((p2, p2.replace(".", "").strip(), 0.95))
    
    # === HIGH SIMILARITY PAIRS (0.7-0.9) ===
    related_pairs = [
        ("The mitochondria produces energy.",
         "Cells need energy to function.", 0.7),
        ("Photosynthesis occurs in plants.",
         "Plants use sunlight for energy.", 0.75),
        ("DNA is a double helix structure.",
         "Genetic information is stored in molecules.", 0.7),
        ("Chemical reactions involve breaking bonds.",
         "Molecules change during reactions.", 0.75),
        ("Force causes acceleration.",
         "Objects accelerate when pushed.", 0.8),
        ("Algorithms solve computational problems.",
         "Computer programs use logic to process data.", 0.7),
    ]
    
    for p1, p2, sim in related_pairs:
        pairs.append((p1, p2, sim))
        pairs.append((p2, p1, sim))
    
    # === LOW SIMILARITY PAIRS (0.2-0.4) ===
    different_topic_pairs = [
        ("The mitochondria is the powerhouse of the cell.",
         "Shakespeare wrote many famous plays.", 0.1),
        ("Water boils at 100 degrees Celsius.",
         "The French Revolution began in 1789.", 0.1),
        ("Photosynthesis produces oxygen.",
         "The stock market fluctuates daily.", 0.05),
        ("Algorithms process data efficiently.",
         "Van Gogh painted Starry Night.", 0.05),
        ("Newton discovered gravity.",
         "Cooking requires proper seasoning.", 0.1),
        # More diverse negatives
        ("DNA is composed of nucleotides.",
         "The Amazon rainforest is the largest.", 0.05),
        ("Electrons orbit the nucleus of an atom.",
         "Mozart composed classical symphonies.", 0.08),
        ("The derivative measures rate of change.",
         "Basketball was invented by James Naismith.", 0.05),
        ("Proteins are made of amino acids.",
         "The Great Wall of China is visible from space.", 0.08),
        ("Chemical reactions involve electron transfer.",
         "Coffee contains caffeine.", 0.1),
        ("The cell membrane is semi-permeable.",
         "World War I started in 1914.", 0.05),
        ("Gravity pulls objects toward Earth.",
         "Jazz music originated in New Orleans.", 0.08),
        ("Enzymes speed up chemical reactions.",
         "The Eiffel Tower is in Paris.", 0.05),
        ("Photons are particles of light.",
         "Dogs are loyal pets.", 0.05),
        ("RNA transcribes genetic information.",
         "The Olympics happen every four years.", 0.08),
        ("Atoms combine to form molecules.",
         "Pizza is a popular food.", 0.05),
        ("The speed of light is constant.",
         "Roses are red flowers.", 0.05),
        ("Mitosis produces two identical cells.",
         "Soccer is the most popular sport.", 0.08),
        ("Acids have low pH values.",
         "The moon orbits the Earth.", 0.15),  # Slightly related (science)
        ("Photosynthesis occurs in chloroplasts.",
         "Rivers flow to the ocean.", 0.12),
    ]
    
    for p1, p2, sim in different_topic_pairs:
        pairs.append((p1, p2, sim))
        pairs.append((p2, p1, sim))
    
    # === SAME SENTENCE PAIRS (similarity = 1.0) ===
    same_sentences = [
        "The quick brown fox jumps over the lazy dog.",
        "Machine learning models require training data.",
        "The experiment demonstrated the hypothesis.",
        "Students should review their notes regularly.",
        "Scientific method involves observation and experimentation.",
    ]
    
    for sent in same_sentences:
        pairs.append((sent, sent, 1.0))
    
    return pairs


def create_exam_answer_data() -> List[Tuple[str, str, float]]:
    """Create synthetic exam answer pairs for training."""
    
    pairs = []
    
    # === COPIED ANSWERS (plagiarism - high similarity) ===
    copied_answers = [
        # Question: Explain photosynthesis
        ("Photosynthesis is the process by which plants convert light energy into chemical energy. "
         "This occurs in the chloroplasts where chlorophyll absorbs sunlight. "
         "The plant uses carbon dioxide and water to produce glucose and oxygen.",
         "Photosynthesis is how plants turn light into chemical energy. "
         "It happens in chloroplasts with chlorophyll absorbing light. "
         "CO2 and H2O are converted to glucose and O2.",
         0.95),
        
        # Question: Describe the water cycle
        ("The water cycle involves evaporation, condensation, and precipitation. "
         "Water evaporates from oceans and lakes, forms clouds, and falls as rain.",
         "Water evaporates from bodies of water, condenses into clouds, "
         "and precipitates as rain. This is the water cycle.",
         0.92),
        
        # Question: Explain Newton's laws
        ("Newton's first law states that an object at rest stays at rest. "
         "The second law shows force equals mass times acceleration. "
         "The third law says every action has an equal and opposite reaction.",
         "Objects remain at rest unless acted upon (Newton's 1st law). "
         "F=ma describes the second law. "
         "For every action there is an equal opposite reaction (3rd law).",
         0.90),
    ]
    
    # === INDEPENDENT ANSWERS (different, but same topic) ===
    independent_answers = [
        # Same question, different genuine answers
        ("Photosynthesis uses sunlight to make food for plants. "
         "The green pigment chlorophyll captures light energy.",
         "Plants need photosynthesis to survive. "
         "Without it, they cannot produce the glucose they need for energy.",
         0.65),
        
        ("The water cycle is nature's way of recycling water. "
         "It ensures fresh water is available for all living things.",
         "Evaporation and condensation are key parts of the water cycle. "
         "Mountains and temperature affect precipitation patterns.",
         0.55),
    ]
    
    # === COMPLETELY DIFFERENT ANSWERS ===
    different_answers = [
        ("Photosynthesis is essential for plant growth and oxygen production.",
         "The American Revolution established democracy in the United States.",
         0.05),
        
        ("Newton's laws explain motion and forces in classical mechanics.",
         "Shakespeare's plays explore themes of love, power, and tragedy.",
         0.08),
    ]
    
    for a1, a2, sim in copied_answers + independent_answers + different_answers:
        pairs.append((a1, a2, sim))
        pairs.append((a2, a1, sim))
    
    return pairs


def augment_data(pairs: List[Tuple[str, str, float]]) -> List[Tuple[str, str, float]]:
    """Augment training data with variations."""
    
    augmented = []
    
    for text1, text2, sim in pairs:
        augmented.append((text1, text2, sim))
        
        # Random word drops (for high similarity pairs)
        if sim > 0.8:
            words1 = text1.split()
            words2 = text2.split()
            
            if len(words1) > 5:
                # Drop 1-2 random words
                drop_idx = random.randint(1, len(words1) - 2)
                modified1 = ' '.join(words1[:drop_idx] + words1[drop_idx+1:])
                augmented.append((modified1, text2, sim * 0.95))
            
            if len(words2) > 5:
                drop_idx = random.randint(1, len(words2) - 2)
                modified2 = ' '.join(words2[:drop_idx] + words2[drop_idx+1:])
                augmented.append((text1, modified2, sim * 0.95))
        
        # Case variations
        augmented.append((text1.lower(), text2.lower(), sim))
        
    return augmented


# =============================================================================
# SIMILARITY LOSS FUNCTIONS
# =============================================================================

class ContrastiveLoss(nn.Module):
    """Contrastive loss for learning similarity with harder margins."""
    
    def __init__(self, margin: float = 0.3, temperature: float = 0.1):
        super().__init__()
        self.margin = margin
        self.temperature = temperature
    
    def forward(self, embeddings1: torch.Tensor, embeddings2: torch.Tensor, 
                labels: torch.Tensor) -> torch.Tensor:
        """
        Args:
            embeddings1: [batch, dim] - embeddings of first texts
            embeddings2: [batch, dim] - embeddings of second texts
            labels: [batch] - similarity scores (0-1)
        """
        # Normalize embeddings
        embeddings1 = F.normalize(embeddings1, p=2, dim=1)
        embeddings2 = F.normalize(embeddings2, p=2, dim=1)
        
        # Cosine similarity
        cos_sim = (embeddings1 * embeddings2).sum(dim=1)  # More stable than cosine_similarity
        
        # For similar pairs (label > 0.5): pull together, target sim = label
        # For dissimilar pairs (label < 0.5): push apart, target sim = 0
        
        # Binary labels for contrastive loss
        is_similar = (labels > 0.5).float()
        
        # Pull similar pairs together
        positive_loss = is_similar * (1 - cos_sim).pow(2)
        
        # Push dissimilar pairs apart with hard margin
        negative_loss = (1 - is_similar) * F.relu(cos_sim - self.margin).pow(2)
        
        return (positive_loss + negative_loss).mean()


class CosineSimilarityLoss(nn.Module):
    """MSE loss between predicted and target similarity."""
    
    def forward(self, embeddings1: torch.Tensor, embeddings2: torch.Tensor,
                targets: torch.Tensor) -> torch.Tensor:
        """
        Args:
            embeddings1: [batch, dim]
            embeddings2: [batch, dim]  
            targets: [batch] - target similarity scores
        """
        predicted_sim = F.cosine_similarity(embeddings1, embeddings2)
        return F.mse_loss(predicted_sim, targets)


# =============================================================================
# SIMILARITY ENCODER
# =============================================================================

class SimilarityEncoder(nn.Module):
    """Wrapper that uses Transformer encoder for text similarity."""
    
    def __init__(self, transformer: Transformer, pooling: str = 'mean', d_model: int = 256):
        super().__init__()
        self.transformer = transformer
        self.pooling = pooling
        self.d_model = d_model
        
        # Projection head for better similarity learning
        self.projection = nn.Sequential(
            nn.Linear(d_model, d_model),
            nn.ReLU(),
            nn.Linear(d_model, d_model // 2),
        )
    
    def encode(self, input_ids: torch.Tensor) -> torch.Tensor:
        """Encode text to embedding vector."""
        # Get encoder output (Transformer.encode handles mask internally)
        encoder_output = self.transformer.encode(input_ids)  # [batch, seq, dim]
        
        # Create mask for pooling (non-padding positions)
        mask = (input_ids != self.transformer.pad_token).float()
        
        # Pool to single vector
        if self.pooling == 'mean':
            # Mean pooling (excluding padding)
            mask_expanded = mask.unsqueeze(-1).expand(encoder_output.size())
            sum_embeddings = (encoder_output * mask_expanded).sum(dim=1)
            sum_mask = mask_expanded.sum(dim=1).clamp(min=1e-9)
            pooled = sum_embeddings / sum_mask
        elif self.pooling == 'cls':
            # First token (CLS-style)
            pooled = encoder_output[:, 0]
        elif self.pooling == 'max':
            # Max pooling
            encoder_output[mask.unsqueeze(-1).expand_as(encoder_output) == 0] = -1e9
            pooled = encoder_output.max(dim=1)[0]
        else:
            raise ValueError(f"Unknown pooling: {self.pooling}")
        
        # Project
        return self.projection(pooled)
    
    def forward(self, text1_ids: torch.Tensor, text2_ids: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        """Encode both texts and return embeddings."""
        emb1 = self.encode(text1_ids)
        emb2 = self.encode(text2_ids)
        return emb1, emb2


# =============================================================================
# TRAINING FUNCTION
# =============================================================================

def train_similarity_model(
    config_name: str = 'small',
    epochs: int = 20,
    batch_size: int = 32,
    learning_rate: float = 1e-4,
    device: str = None,
    save_dir: str = 'checkpoints/similarity'
):
    """
    Train the Transformer for similarity/plagiarism detection.
    """
    
    # Device
    if device is None:
        device = 'cuda' if torch.cuda.is_available() else 'cpu'
    print(f"Training on: {device}")
    
    # Create save directory
    save_path = Path(__file__).parent / save_dir
    save_path.mkdir(parents=True, exist_ok=True)
    
    # === CREATE DATA ===
    print("\n=== Creating Training Data ===")
    paraphrase_pairs = create_paraphrase_data()
    exam_pairs = create_exam_answer_data()
    
    all_pairs = paraphrase_pairs + exam_pairs
    all_pairs = augment_data(all_pairs)
    
    print(f"Total training pairs: {len(all_pairs)}")
    
    # Split train/val
    random.shuffle(all_pairs)
    split_idx = int(len(all_pairs) * 0.9)
    train_pairs = all_pairs[:split_idx]
    val_pairs = all_pairs[split_idx:]
    
    print(f"Training pairs: {len(train_pairs)}")
    print(f"Validation pairs: {len(val_pairs)}")
    
    # === BUILD VOCABULARY ===
    print("\n=== Building Vocabulary ===")
    all_texts = []
    for t1, t2, _ in all_pairs:
        all_texts.extend([t1, t2])
    
    tokenizer = SimpleTokenizer(vocab_size=10000, min_freq=1)
    tokenizer.build_vocab(all_texts)
    print(f"Vocabulary size: {len(tokenizer)}")
    
    # Save tokenizer
    tokenizer.save(str(save_path / 'tokenizer.json'))
    
    # === CREATE DATASETS ===
    train_dataset = SimilarityDataset(train_pairs, tokenizer, max_length=128)
    val_dataset = SimilarityDataset(val_pairs, tokenizer, max_length=128)
    
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size)
    
    # === CREATE MODEL ===
    print("\n=== Creating Model ===")
    
    vocab_size = len(tokenizer)
    
    if config_name == 'tiny':
        # Tiny config
        d_model = 128
        n_heads = 4
        n_layers = 2
        d_ff = 256
    elif config_name == 'small':
        # Small config
        d_model = 256
        n_heads = 4
        n_layers = 4
        d_ff = 512
    else:
        # Base config
        d_model = 512
        n_heads = 8
        n_layers = 6
        d_ff = 2048
    
    transformer = Transformer(
        src_vocab_size=vocab_size,
        tgt_vocab_size=vocab_size,
        d_model=d_model,
        n_heads=n_heads,
        n_encoder_layers=n_layers,
        n_decoder_layers=n_layers,
        d_ff=d_ff,
        max_seq_len=128,
        dropout=0.1,
        pad_token=tokenizer.pad_token_id
    )
    model = SimilarityEncoder(transformer, pooling='mean', d_model=d_model)
    model = model.to(device)
    
    num_params = sum(p.numel() for p in model.parameters())
    print(f"Model parameters: {num_params:,}")
    
    # === TRAINING SETUP ===
    optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=0.01)
    
    total_steps = len(train_loader) * epochs
    scheduler = CosineAnnealingWarmup(
        optimizer,
        warmup_steps=min(500, total_steps // 10),
        total_steps=total_steps
    )
    
    # Use combination of losses
    contrastive_loss_fn = ContrastiveLoss(margin=0.5)
    mse_loss_fn = CosineSimilarityLoss()
    
    # === TRAINING LOOP ===
    print("\n=== Starting Training ===")
    print(f"Epochs: {epochs}")
    print(f"Batch size: {batch_size}")
    print(f"Learning rate: {learning_rate}")
    print("=" * 50)
    
    best_val_loss = float('inf')
    train_losses = []
    val_losses = []
    
    for epoch in range(epochs):
        # Training
        model.train()
        epoch_loss = 0
        
        for batch in train_loader:
            text1 = batch['text1'].to(device)
            text2 = batch['text2'].to(device)
            similarity = batch['similarity'].to(device)
            
            optimizer.zero_grad()
            
            # Forward
            emb1, emb2 = model(text1, text2)
            
            # Combined loss
            loss_contrastive = contrastive_loss_fn(emb1, emb2, similarity)
            loss_mse = mse_loss_fn(emb1, emb2, similarity)
            loss = 0.5 * loss_contrastive + 0.5 * loss_mse
            
            # Backward
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            scheduler.step()
            
            epoch_loss += loss.item()
        
        avg_train_loss = epoch_loss / len(train_loader)
        train_losses.append(avg_train_loss)
        
        # Validation
        model.eval()
        val_loss = 0
        correct_predictions = 0
        total_predictions = 0
        
        with torch.no_grad():
            for batch in val_loader:
                text1 = batch['text1'].to(device)
                text2 = batch['text2'].to(device)
                similarity = batch['similarity'].to(device)
                
                emb1, emb2 = model(text1, text2)
                
                loss_contrastive = contrastive_loss_fn(emb1, emb2, similarity)
                loss_mse = mse_loss_fn(emb1, emb2, similarity)
                loss = 0.5 * loss_contrastive + 0.5 * loss_mse
                
                val_loss += loss.item()
                
                # Check accuracy (predicted similarity within 0.2 of target)
                predicted_sim = F.cosine_similarity(emb1, emb2)
                correct = (torch.abs(predicted_sim - similarity) < 0.2).sum().item()
                correct_predictions += correct
                total_predictions += similarity.size(0)
        
        avg_val_loss = val_loss / len(val_loader)
        val_losses.append(avg_val_loss)
        accuracy = correct_predictions / total_predictions * 100
        
        print(f"Epoch {epoch+1}/{epochs} | "
              f"Train Loss: {avg_train_loss:.4f} | "
              f"Val Loss: {avg_val_loss:.4f} | "
              f"Accuracy: {accuracy:.1f}%")
        
        # Save best model
        if avg_val_loss < best_val_loss:
            best_val_loss = avg_val_loss
            torch.save({
                'epoch': epoch,
                'model_state_dict': model.state_dict(),
                'transformer_state_dict': model.transformer.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'config': {
                    'vocab_size': vocab_size,
                    'd_model': d_model,
                    'n_heads': n_heads,
                    'n_layers': n_layers,
                    'd_ff': d_ff,
                    'config_name': config_name
                },
                'train_loss': avg_train_loss,
                'val_loss': avg_val_loss,
            }, save_path / 'best_model.pt')
            print(f"  ↳ Saved best model!")
    
    # Save final model
    torch.save({
        'epoch': epochs,
        'model_state_dict': model.state_dict(),
        'transformer_state_dict': model.transformer.state_dict(),
        'config': {
            'vocab_size': vocab_size,
            'd_model': d_model,
            'n_heads': n_heads,
            'n_layers': n_layers,
            'd_ff': d_ff,
            'config_name': config_name
        },
        'train_losses': train_losses,
        'val_losses': val_losses,
    }, save_path / 'final_model.pt')
    
    print("\n" + "=" * 50)
    print("Training Complete!")
    print(f"Best validation loss: {best_val_loss:.4f}")
    print(f"Models saved to: {save_path}")
    
    return model, tokenizer


# =============================================================================
# EVALUATION
# =============================================================================

def evaluate_model(model_path: str, device: str = None):
    """Evaluate trained model on test cases."""
    
    if device is None:
        device = 'cuda' if torch.cuda.is_available() else 'cpu'
    
    save_path = Path(model_path)
    
    # Load tokenizer
    tokenizer = SimpleTokenizer()
    tokenizer.load(str(save_path / 'tokenizer.json'))
    
    # Load model
    checkpoint = torch.load(save_path / 'best_model.pt', map_location=device)
    config = checkpoint['config']
    
    transformer = Transformer(
        src_vocab_size=config['vocab_size'],
        tgt_vocab_size=config['vocab_size'],
        d_model=config['d_model'],
        n_heads=config['n_heads'],
        n_encoder_layers=config['n_layers'],
        n_decoder_layers=config['n_layers'],
        d_ff=config['d_ff'],
        max_seq_len=128,
        dropout=0.1,
        pad_token=tokenizer.pad_token_id
    )
    model = SimilarityEncoder(transformer, pooling='mean', d_model=config['d_model'])
    model.load_state_dict(checkpoint['model_state_dict'])
    model = model.to(device)
    model.eval()
    
    print("=" * 60)
    print("SIMILARITY MODEL EVALUATION")
    print("=" * 60)
    
    test_cases = [
        # High similarity (paraphrases)
        ("The mitochondria is the powerhouse of the cell.",
         "Mitochondria produce energy for cells."),
        
        # Medium similarity (related)
        ("Photosynthesis occurs in plant cells.",
         "Plants need sunlight to grow."),
        
        # Low similarity (different topics)
        ("DNA stores genetic information.",
         "The Renaissance was a cultural movement."),
        
        # Same text
        ("Hello world", "Hello world"),
        
        # Exam answer comparison
        ("The water cycle involves evaporation, condensation, and precipitation.",
         "Water evaporates, forms clouds, and falls as rain in a continuous cycle."),
    ]
    
    for text1, text2 in test_cases:
        # Tokenize
        tokens1 = tokenizer.encode(text1)[:128]
        tokens2 = tokenizer.encode(text2)[:128]
        
        # Pad
        tokens1 = tokens1 + [tokenizer.pad_token_id] * (128 - len(tokens1))
        tokens2 = tokens2 + [tokenizer.pad_token_id] * (128 - len(tokens2))
        
        # Convert to tensors
        t1 = torch.tensor([tokens1], dtype=torch.long).to(device)
        t2 = torch.tensor([tokens2], dtype=torch.long).to(device)
        
        # Get similarity
        with torch.no_grad():
            emb1, emb2 = model(t1, t2)
            similarity = F.cosine_similarity(emb1, emb2).item()
        
        print(f"\nText 1: {text1[:60]}...")
        print(f"Text 2: {text2[:60]}...")
        print(f"Similarity: {similarity:.4f}")
        
        if similarity > 0.8:
            print("→ HIGH SIMILARITY (potential plagiarism)")
        elif similarity > 0.5:
            print("→ MODERATE SIMILARITY")
        else:
            print("→ LOW SIMILARITY")
    
    print("\n" + "=" * 60)


# =============================================================================
# MAIN
# =============================================================================

if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="Train Transformer for Plagiarism Detection")
    parser.add_argument('--mode', type=str, default='train', choices=['train', 'evaluate'])
    parser.add_argument('--config', type=str, default='small', choices=['tiny', 'small', 'base'])
    parser.add_argument('--epochs', type=int, default=20)
    parser.add_argument('--batch-size', type=int, default=32)
    parser.add_argument('--lr', type=float, default=1e-4)
    parser.add_argument('--device', type=str, default=None)
    parser.add_argument('--save-dir', type=str, default='checkpoints/similarity')
    
    args = parser.parse_args()
    
    if args.mode == 'train':
        model, tokenizer = train_similarity_model(
            config_name=args.config,
            epochs=args.epochs,
            batch_size=args.batch_size,
            learning_rate=args.lr,
            device=args.device,
            save_dir=args.save_dir
        )
        
        # Run evaluation after training
        save_path = Path(__file__).parent / args.save_dir
        evaluate_model(str(save_path), device=args.device)
        
    elif args.mode == 'evaluate':
        save_path = Path(__file__).parent / args.save_dir
        evaluate_model(str(save_path), device=args.device)
